### ISSUE TITLE
double dipping

### ISSUE THREAD

**Issue by pete-hulson** [JaneSullivan-NOAA/rema#6]
https://github.com/JaneSullivan-NOAA/rema/blob/93bb1d40123856ed2f503038673180ee82c5b53d/src/rema.cpp#L114

change these next couple lines to:

  //log_biomass_sd = biomass_cv.array() * biomass_cv.array() + Type(1.0);
  //log_biomass_sd = sqrt(log(log_biomass_sd.array()));
  log_biomass_sd = biomass_cv.array();

basically what's happening is that your doing the normal -> lognormal transformation of sd twice. The values coming out of the rwout.rep file has already done this in the tpl and by doing it again it's 'double dipping', or 'double transforming', which I guess is the ultimate transformer :) anyway, when you take this out the likelihoods from admb and tmb match up (the dnorm, like you said, is doing everything the same too).

k, so a suggestion for down the road might be to pull the data out the the re.dat file (which is why i just commented out those lines rather than take them out so maybe you can do that in the future). i think the reason you're using the rwout is cause you can compare model results. don't necessarily need to do that now, but, going forward and thinking about making this into some production script maybe we can build a function that pulls the input data directly from racebase, basically merging a few steps compared to what we currently do, and then populates the input data from that rather than relying on running an admb model to then use the output (you're prolly already two steps ahead of me on this tho).

still doesn't solve the underlying issue tho...

**Comment by JaneSullivan-NOAA** [comment]
addressed by https://github.com/JaneSullivan-NOAA/rema/commit/23f74dfb342d23ed9755d484dbf4a4788377bb7d
