### ISSUE TITLE
double dipping 2

### ISSUE THREAD

**Issue by pete-hulson** [JaneSullivan-NOAA/rema#7]
https://github.com/JaneSullivan-NOAA/rema/blob/93bb1d40123856ed2f503038673180ee82c5b53d/src/rema.cpp#L125

same as last issue, change these next couple lines to:

  //log_cpue_sd = cpue_cv.array() * cpue_cv.array() + Type(1.0);
  //log_cpue_sd = sqrt(log(log_cpue_sd.array()));
  log_cpue_sd = cpue_cv.array();

**Comment by JaneSullivan-NOAA** [comment]
addressed by https://github.com/JaneSullivan-NOAA/rema/commit/23f74dfb342d23ed9755d484dbf4a4788377bb7d
